[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/login.html"
  status = 302
  conditions = {Role = ["!admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  conditions = {Role = ["admin"]}
