[build]
  base = ""
  publish = "."
  functions = "netlify/functions"


[[redirects]]
  from = "/admin/*"
  to = "/admin/login.html"
  status = 302
  conditions = {Role = ["!admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  conditions = {Role = ["admin"]}

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

